services:
  db:
    image: postgres:15-alpine
    container_name: pro_gas_db_local
    restart: always
    environment:
      POSTGRES_USER: victo
      POSTGRES_PASSWORD: local_password
      POSTGRES_DB: pro_gas_erp
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: