"""auditoria_neon_final

Revision ID: 63b609a19722
Revises: b1f4e8a3c920
Create Date: 2026-05-16 21:17:21.748255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '63b609a19722'
down_revision: Union[str, Sequence[str], None] = 'b1f4e8a3c920'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing = inspector.get_table_names()

    if 'medias_cargas_historial' not in existing:
        op.create_table('medias_cargas_historial',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('media_carga_id', sa.Integer(), nullable=True),
        sa.Column('numero_guia', sa.String(), nullable=False),
        sa.Column('proveedor', sa.String(), nullable=False),
        sa.Column('fecha_documento', sa.DateTime(), nullable=False),
        sa.Column('total_neto', sa.Integer(), nullable=False),
        sa.Column('total_iva', sa.Integer(), nullable=False),
        sa.Column('total_bruto', sa.Integer(), nullable=False),
        sa.Column('kilos_totales', sa.Numeric(precision=10, scale=3), nullable=False),
        sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('registrado_por_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['media_carga_id'], ['medias_cargas.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['registrado_por_id'], ['usuarios.id'], ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index('ix_mc_hist_proveedor_fecha', 'medias_cargas_historial', ['proveedor', 'fecha_registro'], unique=False)
        op.create_index(op.f('ix_medias_cargas_historial_fecha_registro'), 'medias_cargas_historial', ['fecha_registro'], unique=False)
        op.create_index(op.f('ix_medias_cargas_historial_media_carga_id'), 'medias_cargas_historial', ['media_carga_id'], unique=False)
        op.create_index(op.f('ix_medias_cargas_historial_numero_guia'), 'medias_cargas_historial', ['numero_guia'], unique=False)
        op.create_index(op.f('ix_medias_cargas_historial_registrado_por_id'), 'medias_cargas_historial', ['registrado_por_id'], unique=False)

    if 'medias_cargas_historial_lineas' not in existing:
        op.create_table('medias_cargas_historial_lineas',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('historial_id', sa.Integer(), nullable=False),
        sa.Column('formato_producto', sa.String(), nullable=False),
        sa.Column('cantidad_llenos', sa.Integer(), nullable=False),
        sa.Column('cantidad_vacios', sa.Integer(), nullable=False),
        sa.Column('precio_unitario_neto', sa.Integer(), nullable=False),
        sa.Column('kilos_linea', sa.Numeric(precision=10, scale=3), nullable=False),
        sa.Column('subtotal_neto', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['historial_id'], ['medias_cargas_historial.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_medias_cargas_historial_lineas_historial_id'), 'medias_cargas_historial_lineas', ['historial_id'], unique=False)

    if 'tratados_comerciales_backup' in existing:
        op.drop_table('tratados_comerciales_backup')

    if 'tratados_comerciales' in existing:
        op.drop_index(op.f('ix_tratados_comerciales_rut_cliente'), table_name='tratados_comerciales')
        op.drop_table('tratados_comerciales')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tratados_comerciales',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rut_cliente', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('nombre_cliente', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('formato_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('descuento_por_kilo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('vigente', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.CheckConstraint('descuento_por_kilo >= 0::double precision', name=op.f('ck_descuento_non_negative')),
    sa.ForeignKeyConstraint(['admin_id'], ['usuarios.id'], name=op.f('tratados_comerciales_admin_id_fkey')),
    sa.ForeignKeyConstraint(['formato_id'], ['productos_maestro.id'], name=op.f('tratados_comerciales_formato_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tratados_comerciales_pkey'))
    )
    op.create_index(op.f('ix_tratados_comerciales_rut_cliente'), 'tratados_comerciales', ['rut_cliente'], unique=False)
    op.create_table('tratados_comerciales_backup',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rut_cliente', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('nombre_cliente', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('formato_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('descuento_por_kilo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('vigente', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('backup_timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True)
    )
    op.drop_index(op.f('ix_medias_cargas_historial_lineas_historial_id'), table_name='medias_cargas_historial_lineas')
    op.drop_table('medias_cargas_historial_lineas')
    op.drop_index(op.f('ix_medias_cargas_historial_registrado_por_id'), table_name='medias_cargas_historial')
    op.drop_index(op.f('ix_medias_cargas_historial_numero_guia'), table_name='medias_cargas_historial')
    op.drop_index(op.f('ix_medias_cargas_historial_media_carga_id'), table_name='medias_cargas_historial')
    op.drop_index(op.f('ix_medias_cargas_historial_fecha_registro'), table_name='medias_cargas_historial')
    op.drop_index('ix_mc_hist_proveedor_fecha', table_name='medias_cargas_historial')
    op.drop_table('medias_cargas_historial')
    # ### end Alembic commands ###
