"""add created_at to
  ventas_revendedor

Revision ID: 68605517dcbb
Revises: a8010b482550
Create Date: 2026-05-16 02:14:17.046713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68605517dcbb'
down_revision: Union[str, Sequence[str], None] = 'a8010b482550'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ventas_revendedor', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ventas_revendedor', 'created_at')
    # ### end Alembic commands ###
