"""feat: add proveedor to medias_cargas

Revision ID: 6d75018a1cbb
Revises: 968712c8d7a3
Create Date: 2026-05-10 22:23:58.009706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d75018a1cbb'
down_revision: Union[str, Sequence[str], None] = '968712c8d7a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medias_cargas', sa.Column('proveedor', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medias_cargas', 'proveedor')
    # ### end Alembic commands ###
