"""be08_tratados_comerciales_descuento_por_kilo

Revision ID: 7b2d77fdad1b
Revises: 7f873477576e
Create Date: 2026-04-18 20:33:51.775470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b2d77fdad1b'
down_revision: Union[str, Sequence[str], None] = '7f873477576e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tratados_comerciales', sa.Column('descuento_por_kilo', sa.Float(), nullable=False))
    op.add_column('tratados_comerciales', sa.Column('vigente', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_tratados_comerciales_rut_cliente'), 'tratados_comerciales', ['rut_cliente'], unique=False)
    op.drop_column('tratados_comerciales', 'precio_pactado')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tratados_comerciales', sa.Column('precio_pactado', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_tratados_comerciales_rut_cliente'), table_name='tratados_comerciales')
    op.drop_column('tratados_comerciales', 'vigente')
    op.drop_column('tratados_comerciales', 'descuento_por_kilo')
    # ### end Alembic commands ###
