"""add cuadre fields to cierres_diarios

Revision ID: 7f873477576e
Revises: 9fd9332f4d0c
Create Date: 2026-04-18 20:28:23.464339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f873477576e'
down_revision: Union[str, Sequence[str], None] = '9fd9332f4d0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cierres_diarios', sa.Column('diferencia', sa.Integer(), nullable=True))
    op.add_column('cierres_diarios', sa.Column('estado_cuadre', sa.String(), nullable=True))
    op.add_column('cierres_diarios', sa.Column('stock_snapshot', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cierres_diarios', 'stock_snapshot')
    op.drop_column('cierres_diarios', 'estado_cuadre')
    op.drop_column('cierres_diarios', 'diferencia')
    # ### end Alembic commands ###
