"""implementacion_mer_oficial

Revision ID: 9fd9332f4d0c
Revises: 
Create Date: 2026-04-18 17:47:34.841957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fd9332f4d0c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productos_maestro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('formato', sa.String(), nullable=False),
    sa.Column('peso_kg', sa.Float(), nullable=False),
    sa.Column('precio_publico_base', sa.Integer(), nullable=False),
    sa.Column('stock_llenos', sa.Integer(), nullable=False),
    sa.Column('stock_vacios', sa.Integer(), nullable=False),
    sa.CheckConstraint('stock_llenos >= 0', name='ck_stock_llenos_non_negative'),
    sa.CheckConstraint('stock_vacios >= 0', name='ck_stock_vacios_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bitacora_llamadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_nombre', sa.String(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=False),
    sa.Column('direccion', sa.String(), nullable=False),
    sa.Column('detalle_pedido', sa.Text(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cierres_diarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chofer_nombre', sa.String(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('efectivo_rendido', sa.Integer(), nullable=False),
    sa.Column('vouchers_transbank', sa.Integer(), nullable=False),
    sa.Column('descuentos', sa.Integer(), nullable=False),
    sa.Column('total_ventas_calc', sa.Integer(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medias_cargas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_guia', sa.String(), nullable=False),
    sa.Column('total_neto', sa.Integer(), nullable=False),
    sa.Column('total_iva', sa.Integer(), nullable=False),
    sa.Column('total_bruto', sa.Integer(), nullable=False),
    sa.Column('kilos_totales', sa.Float(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tratados_comerciales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rut_cliente', sa.String(), nullable=False),
    sa.Column('nombre_cliente', sa.String(), nullable=False),
    sa.Column('formato_id', sa.Integer(), nullable=False),
    sa.Column('precio_pactado', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['formato_id'], ['productos_maestro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Add columns with a temporary server_default so existing rows don't violate NOT NULL.
    op.add_column('usuarios', sa.Column('password_hash', sa.String(), nullable=False, server_default=''))
    op.add_column('usuarios', sa.Column('rol', sa.String(), nullable=False, server_default='operador'))
    op.add_column('usuarios', sa.Column('estado', sa.Boolean(), nullable=False, server_default=sa.true()))
    # Remove the server defaults — application code is responsible for providing values.
    op.alter_column('usuarios', 'password_hash', server_default=None)
    op.alter_column('usuarios', 'rol', server_default=None)
    op.alter_column('usuarios', 'estado', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'estado')
    op.drop_column('usuarios', 'rol')
    op.drop_column('usuarios', 'password_hash')
    op.drop_table('tratados_comerciales')
    op.drop_table('medias_cargas')
    op.drop_table('cierres_diarios')
    op.drop_table('bitacora_llamadas')
    op.drop_table('productos_maestro')
    # ### end Alembic commands ###
