"""add_audit_fields_to_cierres_diarios

Revision ID: a8010b482550
Revises: 6d75018a1cbb
Create Date: 2026-05-15 21:45:51.500987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8010b482550'
down_revision: Union[str, Sequence[str], None] = '6d75018a1cbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cierres_diarios', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('cierres_diarios', sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('cierres_diarios', sa.Column('cerrado_por_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_cierres_diarios_cerrado_por_id', 'cierres_diarios', 'usuarios', ['cerrado_por_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_cierres_diarios_cerrado_por_id', 'cierres_diarios', type_='foreignkey')
    op.drop_column('cierres_diarios', 'cerrado_por_id')
    op.drop_column('cierres_diarios', 'closed_at')
    op.drop_column('cierres_diarios', 'created_at')
    # ### end Alembic commands ###
